### ISSUE TITLE
Why Lykon/DreamShaper doesn't work anymore?

### ISSUE THREAD

**Issue by WalidAliAlfaid** [geocine/sd-easy-mode#20]
is it because of the updates and if so how can i use the old version please

**Comment by geocine** [comment]
It seems like this might be due to an update in the diffuser dependency, considering I haven't made updates to this repository in quite a while. Additionally, when I looked at the https://huggingface.co/Lykon/DreamShaper/tree/main branch, I noticed the setup is quite unusual, with the models spread out in different places.
