### ISSUE TITLE
Can I retrain my model that I previously trained in "sd-easy-mode" with new datashets?

### ISSUE THREAD

**Issue by Damarcreative** [geocine/sd-easy-mode#21]
At the bottom of the variable "SSD_TOKEN" there is a variable "MODEL_NAME = "runwayml/stable-diffusion-v1-5" ", by the way if I replace it with my previous model which was trained in "sd-easy-mode" will that work?? to improve previous model with new dataset??
the model I trained before: tensor-diffusion/melaura-v1.0

```
BRANCH = "main" # Branch/Tag of the repository to use
SDD_TOKEN = "melaura" # @param {type:"string"}
# MODEL_NAME = "runwayml/stable-diffusion-v1-5" # Base model you want to use, only diffusers model
MODEL_NAME = "tensor-diffusion/melaura-v1.0" # @param {type:"string"}
```

**Comment by geocine** [comment]
Feel free to give it a try, but please note that my support is limited to `runwayml/stable-diffusion-v1-5` due to the vast number of models available. I would caution against retraining your model without careful consideration, as this can introduce bias and potentially lead to overfitting, which could compromise the model's generalization capabilities and performance on unseen data.
